# Generated by Django 5.1.2 on 2024-11-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_apellidom_usuario_apellidop_usuario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidom',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
